### ISSUE TITLE
The `do_queue` deprecation in PennyLane breaks Catalyst tests

### ISSUE THREAD

**Issue by maliasadi** [PennyLaneAI/catalyst#145]
Looks like the [do_queue deprecation](https://github.com/PennyLaneAI/pennylane/pull/4148) in PennyLane led to failed tests in Catalyst. The error messages using PennyLane `0.31.0-dev`:
```console
warnings.warn(do_queue_deprecation_warning, UserWarning)
jax._src.traceback_util.UnfilteredStackTrace: UserWarning: The do_queue keyword argument is deprecated. Instead of setting it to False, use qml.queuing.QueuingManager.stop_recording()
```

**Comment by erick-xanadu** [comment]
Just a note, the tests that are failing are failing because we explicitly check that no warnings are issued when re-compilation is unnecessary via type promotion. If recompilation happens, a warning is issued. We still need to make sure to remove our dependency on the `do_queue=False` to avoid the future deprecation, but the tests can succeed by making the filter more specific towards the recompilation warning.

**Comment by maliasadi** [comment]
@erick-xanadu yes, indeed! Fixed this in the PR following the recommended way.
