### ISSUE TITLE
`TensorProd` alignment issue

### ISSUE THREAD

**Issue by multiphaseCFD** [PennyLaneAI/catalyst#405]
#### Issue description

* *Expected behavior:* A `TensorProd` observable passed to a Lightning backend should work the same way as a same `TensorProd` observable created in a Lightning backend.

* *Actual behavior:* 
```
    constexpr size_t num_shots = 10;
    sim->SetDeviceShots(num_shots);
    ObsIdType px = sim->Observable(ObsId::PauliX, {}, {Qs[2]});
    ObsIdType py = sim->Observable(ObsId::PauliY, {}, {Qs[1]});
    ObsIdType pz = sim->Observable(ObsId::PauliZ, {}, {Qs[0]});
    ObsIdType txyz = sim->TensorObservable({px, py, pz});
    auto result = sim->Var(txyz); 
```
Tested the code above with [ac496f9](https://github.com/PennyLaneAI/pennylane-lightning/pull/577/commits/ac496f92beb5f32038f3c47472423f3dc355663a) and [6f6603b](https://github.com/PennyLaneAI/catalyst/pull/392/commits/6f6603b38269f6959f25cfc640ffa1ae44879320), the message thrown is 
```
obs_ in var size********:1
ob name in applySHOTS:PauliX[2]
ob name in applySHOTS:PauliY[1]
ob name in applySHOTS:PauliZ[0]
ob name in applySHOTS:PauliX[2] @ PauliY[1] @ PauliZ[0] 

```

However, the the expected message is

```
obs_ in var size********:3
ob name in applySHOTS:PauliX[2]
ob name in applySHOTS:PauliY[1]
ob name in applySHOTS:PauliZ[0]
```

* *Reproduces how often:*   Always

* *System information:* 

```
Platform info:           macOS-14.2-arm64-arm-64bit
Python version:          3.11.1
Numpy version:           1.23.5
Scipy version:           1.10.0
```

#### Additional information

Note that this issue impacts the shot-measurement support for PR [392](https://github.com/PennyLaneAI/catalyst/pull/392).

**Comment by maliasadi** [comment]
Thanks @multiphaseCFD for creating the issue! I dig in a little bit more and can confirm this issue is related to the misuse of `std::shared_ptr` in `TensorProd::create` and its integration with Catalyst. I'll share the patch when I properly test it. But, as we discussed offline, another related issue is regarding the inconsistency between the support in analytic and finite-shots modes. With the same alignment for TensorProd, the analytic mode works just fine :thinking:

**Comment by maliasadi** [comment]
I fixed the issue in both Lightning and Catalyst, please check https://github.com/PennyLaneAI/pennylane-lightning/pull/577 and #392. 

A couple of lessons were learned from this issue,
- Using variadic (w/ generic) constructors for the `TensorProdObs` class in Lightning can be reconsidered as they can be problematic if there's not any strategy for capturing corner cases of these constructors. In the past, `TensorProdObs` wasn't intended to be used as a public API, but now, with its use case in Catalyst, we should ensure users cannot misuse these constructors. I've added some constraints for these arguments to ensure consistency and support.

- No one should mix `std::make_shared` with `std::shared_ptr` instances without understanding what they are doing :) In Catalyst, we use the recommended `TensorProdObs::create` wrapper function around the constructor of `TensorProdObs` in the observable manager of the runtime. This wrapper function is part of the public API for `TensorProdObs` and we used it without noticing this wrapper returns a `shared_ptr` (not a regular ptr so that can be used to create a shared ptr). In Catalyst, we use `std::make_shared` method to create shared pointers for all of observables as others don't return a `shared_ptr` nor expose any wrapper function. So, using `std::make_shared` and `TensorProdObs::create`  triggers the `TensorProdObs` constructor twice with not throwing any issues as the constructor accepts any generic arguments. I've updated the Catalyst observable manager class by removing `std::make_shared` as the `TensorProdObs::create` returns a shared pointer and that's sufficient.
