### ISSUE TITLE
Automatically transform in-place array assignments using autograph

### ISSUE THREAD

**Issue by dime10** [PennyLaneAI/catalyst#516]
### Context

Catalyst uses a source-to-source transformation package called [AutoGraph](https://docs.pennylane.ai/projects/catalyst/en/stable/dev/autograph.html), which allows users to write regular Python code that is automagically transformed into JAX-style traceable code. For example, the following for loop can automatically be compiled by Catalyst to execute at run-time using the `autograph` option, whereas we would otherwise need to explicitly use the [functional form](https://docs.pennylane.ai/projects/catalyst/en/stable/code/api/catalyst.for_loop.html):

```py
from catalyst import *

@qjit(autograph=True)
def f(n: int):
    for i in range(n):
        debug.print(i)

f(5)
```

We would like to extend the current AutoGraph support to apply to array updates as is typically done with Numpy arrays:

```py
import numpy as np

x = np.zeros(10)
y = np.array([3, 2, 5])

# update some elements of x with y
x[4:7] = y
```

Attempting to do the same with JAX arrays will raise the following error:

```pycon
TypeError: '<class 'jaxlib.xla_extension.ArrayImpl'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html
```

Instead, JAX requires that a new array be created with the `.at` style notation (which can optionally be reassigned to the old array):

```py
import jax.numpy as jnp

x = jnp.zeros(10)
y = jnp.array([3, 2, 5])

# update some elements of x with y
x = x.at[4:7].set(y)
```

### Goal

We would like the array updates to be automatically converted to the required JAX style when the `autograph` flag is set to True. The following example demonstrates this feature:

```py
@qjit(autograph=True)
def expand_by_two(x):
    """Expand the first dimension of x to twice the size and broadcast the contents."""
    
    first_dim = x.shape[0]
    result = jnp.empty((first_dim*2, *x.shape[1:]), dtype=x.dtype)

    for i in range(2):
        start = i * first_dim
        stop = start + first_dim
        result[start:stop] = x

    return result

>>> expand_by_two(jnp.array([5, 3, 4]))
Array([5, 3, 4, 5, 3, 4], dtype=int64)
```

Requirements:
- the feature only needs to work with regular assignments, `+=`, `*=`, etc. are not required
- if the assigned-to object is not a JAX array, the implementation should fall back to the regular Python operator
- the [AutoGraph guide](https://github.com/PennyLaneAI/catalyst/blob/main/doc/dev/autograph.rst) should be updated 

### Technical details

- AutoGraph works by identifying specific patterns in the AST of a given Python function and replacing them with calls to pre-determined operator. By providing our own implementation of these operators we can change the behaviour of existing code, including of Python built-ins.
- The main object that manages the AutoGraph transformations in Catalyst is the [CFTransformer](https://github.com/PennyLaneAI/catalyst/blob/d1a5ce5c16b23f3ba79e15f775f7b889dd7df6cf/frontend/catalyst/autograph.py#L37)
- Implementations for overloaded operators in Catalyst are provided in the [ag_primitives.py](https://github.com/PennyLaneAI/catalyst/blob/main/frontend/catalyst/ag_primitives.py) module.
- AutoGraph has an overloadable `set_item` operator ([example implementation](https://github.com/tensorflow/tensorflow/blob/8b01d2cfb1ee5140dd5bbe58c98d5cb8ba1a03f9/tensorflow/python/autograph/operators/slices.py#L96) from TensorFlow) which requires the [List Feature](https://github.com/tensorflow/tensorflow/blob/8b01d2cfb1ee5140dd5bbe58c98d5cb8ba1a03f9/tensorflow/python/autograph/converters/lists.py#L47). This operator should allow us to implement the desired functionality.

When working on AutoGraph features it is particularly important to pay attention to edge cases and include comprehensive test cases.

_Note that this issue does not require installing Catalyst from source. The PyPI wheel can simply be downloaded and installed/extracted, and the Python files modified in-place. The optional dependency on `tensorflow` needs to be separately installed._

**Comment by cole-k** [comment]
I've encountered some difficulty with implementing this feature as described in the issue.

I'm including all of the details of what I've attempted. If you would like I can additionally commit and push my (messy) work to a fork; so far I have been editing the source files in the wheel as you suggested.

### Test case used
I converted your example case into a test case, which I tested against in `frontend/test/pytest/test_autograph.py`.

```python
    def test_array_set(self):
        @qjit(autograph=True)
        def fn(x):
            """Expand the first dimension of x to twice the size and broadcast the contents."""

            first_dim = x.shape[0]
            result = jnp.empty((first_dim*2, *x.shape[1:]), dtype=x.dtype)

            for i in range(2):
                start = i * first_dim
                stop = start + first_dim
                result[start:stop] = x

            return result

        check_cache(fn.original_function)
        assert fn(jnp.array([5, 3, 4])) == jnp.array([5, 3, 4, 5, 3, 4])
```

### Problem 1: Wrong converter?
I stubbed out an implementation of `set_item` as suggested in the **Technical details**.

I noticed that this function seemed to not get invoked in my testing.

It seems like there was a typo in the description and the actual converter is [the slices converter](https://github.com/tensorflow/tensorflow/blob/8b01d2cfb1ee5140dd5bbe58c98d5cb8ba1a03f9/tensorflow/python/autograph/converters/slices.py).

If this is not the case, then I think I am rather confused. Let me know what I can do to make my confusion clear (e.g. pushing my code to a fork).

### Problem 2: `get_item`
If I use the slices converter, then it also converts

```python
first_dim = x.shape[0]
```
into
```python
first_dim = ag__.get_item(x.shape, 0, opts=ag__.GetItemOpts(element_dtype=None))
```

which is fine by me because I can make an implementation of `get_item` too.

However, I'm not too sure how to pass the `opts` around. It seems tensorflow uses to propagate information about the type of the element (see [this function](https://github.com/tensorflow/tensorflow/blob/8b01d2cfb1ee5140dd5bbe58c98d5cb8ba1a03f9/tensorflow/python/autograph/operators/slices.py#L71-L77)), but I did not investigate it in careful detail because `get_item` on the whole seems to be secondary to this issue.

I'm inclined to simplify the test example you provided (when I use it for my own tests) to avoid dealing with the `opts` argument correctly, but if you know of an obvious way to handle this I'm happy to implement `get_item` too.

### Problem 3: `set_item`
Even when I simplify the code to something like

```python
@qjit(autograph=True)
def fn(x, y):
  x[:] = y
  return x
```

I still see the error you describe:

```python
TypeError: '<class 'jax._src.interpreters.partial_eval.DynamicJaxprTracer'>' object does not support item assignment. JAX arrays are immutable. Instead of ``x[idx] = y``, use ``x = x.at[idx].set(y)`` or another .at[] method: https://jax.readthedocs.io/en/latest/_autosummary/jax.numpy.ndarray.at.html
```

The (relevant) part of the translated code appears to still be

```python
x[:] = y
```

I'm confused because I would expect this to have been translated to

```python
ag__set_item(x, SomeIndex(), y)
```
since I am using

```python
node = slices.transform(node, ctx)
```

to transform the AST (per **Problem 1**).

I additionally tried `lists.transform` just in case I missed something, but that didn't seem to do anything.

---

I would prefer to have submitted a PR for this, but I've spent more than a couple hours across tracing things and referring to documentation already. Were I being paid to work on this issue, I probably would have reached out a little earlier.

**Comment by dime10** [comment]
Hmm, so the `SliceTransformer` doesn't support slicing?

A bit strange, but that's alright. We can just restrict a first implementation of this feature to only support single indices :)

Thanks for the investigation!
